dist: trusty
sudo: required
language: scala
scala:
- 2.11.8
script:
  - sbt "it:test-only repositories.fileupload.FileUploadRepositorySpec"
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org=3.2.10

before_script:
  - sudo service mongod restart
#  - ps fauxwwwww
#  - sudo pkill mongod
#  - sudo apt-get install -y mongodb-org=3.2.10 mongodb-org-server=3.2.10 mongodb-org-shell=3.2.10 mongodb-org-mongos=3.2.10 mongodb-org-tools=3.2.10
#  - sudo service mongod start
